# Generated by Django 5.0.7 on 2024-08-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_productimage_secondary_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={},
        ),
    ]
