# Generated by Django 5.0.7 on 2024-08-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='quaternary_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/additional/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='tertiary_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/additional/'),
        ),
    ]
