# Generated by Django 5.0.7 on 2024-08-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_product_image_url_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
