# Generated by Django 5.0.7 on 2024-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_customuser_last_name_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
