# Generated by Django 5.0.7 on 2024-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_customuser_email_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name_updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name_email_updated_at',
            field=models.JSONField(default=dict),
        ),
    ]
