# Generated by Django 5.0.7 on 2024-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_customuser_email_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name_email_updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
