# Generated by Django 5.0.7 on 2024-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_customuser_name_email_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fields_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
