# Generated by Django 5.0.7 on 2024-09-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_customuser_fields_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fields_disabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name_updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name_updated_at',
        ),
    ]
