# Generated by Django 5.0.7 on 2024-09-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_remove_shippingaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_method_id',
        ),
    ]
