# Generated by Django 5.1.7 on 2025-09-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_paymentdetail_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.paymentmethod'),
            preserve_default=False,
        ),
    ]
