# Generated by Django 5.1.7 on 2025-09-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_paymentmethod_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abroad_delivery_days',
            field=models.PositiveIntegerField(blank=True, help_text="Estimated delivery days for orders from abroad. Only applies if 'Is Abroad Order' is checked.", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_abroad_order',
            field=models.BooleanField(default=False),
        ),
    ]
