# Generated by Django 5.1.7 on 2025-09-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_order_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
