# Generated by Django 5.1.7 on 2025-09-15 19:18

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_abroad_delivery_days_product_is_abroad_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='quaternary_image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='secondary_image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='tertiary_image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
    ]
