# Generated by Django 5.1.7 on 2025-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_category_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imei_or_serial', models.CharField(max_length=200, unique=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
