# Generated by Django 5.1.7 on 2025-09-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_method_id',
        ),
    ]
