# Generated by Django 5.1.7 on 2025-11-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_secretproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretproduct',
            name='notes',
        ),
    ]
