# Generated by Django 5.1.7 on 2026-05-20 14:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='quaternary_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='secondary_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='tertiary_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/additional/'),
        ),
    ]
